// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdhxjgeabpw86fD03L6COX76WurzZEvcU',
    appId: '1:576926243486:web:e02b3abc8a30fd6718798f',
    messagingSenderId: '576926243486',
    projectId: 'ccu-final-project',
    authDomain: 'ccu-final-project.firebaseapp.com',
    storageBucket: 'ccu-final-project.appspot.com',
    measurementId: 'G-YXJC74S5YG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_GJZ086MT2Ccu_DHYs4aSEkidMn1IApY',
    appId: '1:576926243486:android:6d465a8b2335e5b018798f',
    messagingSenderId: '576926243486',
    projectId: 'ccu-final-project',
    storageBucket: 'ccu-final-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5P0q7M_S-2nQ7M9S4wfEndzBDuDmK18Q',
    appId: '1:576926243486:ios:06b57b3544e8dcd018798f',
    messagingSenderId: '576926243486',
    projectId: 'ccu-final-project',
    storageBucket: 'ccu-final-project.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5P0q7M_S-2nQ7M9S4wfEndzBDuDmK18Q',
    appId: '1:576926243486:ios:06b57b3544e8dcd018798f',
    messagingSenderId: '576926243486',
    projectId: 'ccu-final-project',
    storageBucket: 'ccu-final-project.appspot.com',
    iosBundleId: 'com.example.finalProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdhxjgeabpw86fD03L6COX76WurzZEvcU',
    appId: '1:576926243486:web:fb119c8d12ced72d18798f',
    messagingSenderId: '576926243486',
    projectId: 'ccu-final-project',
    authDomain: 'ccu-final-project.firebaseapp.com',
    storageBucket: 'ccu-final-project.appspot.com',
    measurementId: 'G-M11MQY39PC',
  );
}
